### ISSUE TITLE
Unable to run the tests

### ISSUE THREAD

**Issue by lra** [tobami/codespeed#153]
I'm working on a mac with homebrew's python.

When cloning master I get so many errors running the tests that they are not worth pointing them out.

I do:
```bash
git clone git@github.com:tobami/codespeed.git
[...]
pip install -r codespeed/requirements.txt
[...]
cd codespeed
python setup.py install
[...]
python manage.py syncdb
[...]
python manage.py migrate
[...]
python manage.py test
[...]
```
And I get:
```
Ran 411 tests in 10.480s

FAILED (failures=2, errors=178, skipped=1, expected failures=1)
Destroying test database for alias 'default'...
```

A lot of errors are about:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/codespeed-0.9.1-py2.7.egg/codespeed/tests/tests_api.py", line 38, in setUp
    username='apiuser', email='api@foo.bar', password='password')
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 186, in create_user
    user.save(using=self._db)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 664, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 170, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python2.7/site-packages/tastypie/models.py", line 62, in create_api_key
    ApiKey.objects.create(user=kwargs.get('instance'))
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 149, in create
    return self.get_query_set().create(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 414, in create
    obj = self.model(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 397, in __init__
    val = field.get_default()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 391, in get_default
    return self.default()
  File "/usr/local/lib/python2.7/site-packages/tastypie/utils/timezone.py", line 21, in now
    return timezone.localtime(timezone.now())
  File "/usr/local/lib/python2.7/site-packages/django/utils/timezone.py", line 237, in localtime
    value = value.astimezone(timezone)
ValueError: astimezone() cannot be applied to a naive datetime
```
But not all

**Comment by tobami** [comment]
This was fixed by the removal of the incomplete tastypie based API
