### ISSUE TITLE
Exception during report generation due to long summary

### ISSUE THREAD

**Issue by Quasilyte** [tobami/codespeed#241]
The 64 char limit can be limitating for benchmarks with long names.

For example, suppose we have a package `github.com/ethereum/go-ethereum/common/bitutil` and benchmark `Encoding4KBVerySparse` inside it.
Using straightforward approach, benchmark name becomes:
`github.com/ethereum/go-ethereum/common/bitutil/Encoding4KBVerySparse`.
I actually append metric name to it, so in reallity it's
`github.com/ethereum/go-ethereum/common/bitutil/Encoding4KBVerySparse:Time`. :)

Names that long are probably a bad idea, but still, 64 seems not enough.

Example summary (83 chars):
```
github.com/ethereum/go-ethereum/common/bitutil/Encoding4KBVerySparse:Time down 3.6%
```

Here is the call stack:
```
ERROR:django.request:Internal Server Error: /result/add/json/
Traceback (most recent call last):
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/localdisk/users/isharipo/gospeed/codespeed/auth.py", line 42, in _decorator
    return func(request, *args, **kwargs)
  File "/localdisk/users/isharipo/gospeed/codespeed/views.py", line 796, in add_json_results
    create_report_if_enough_data(rep[0], rep[1], rep[2])
  File "/localdisk/users/isharipo/gospeed/codespeed/results.py", line 152, in create_report_if_enough_data
    executable=exe, environment=e, revision=rev
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/db/models/query.py", line 498, in _create_object_from_params
    obj = self.create(**params)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/localdisk/users/isharipo/gospeed/codespeed/models.py", line 261, in save
    super(Report, self).save(*args, **kwargs)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/nfs/site/home/isharipo/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(64)
```

**Comment by Quasilyte** [comment]
Making up a "short name" is possible, but it will make data in DB translated from the original, so one can't easily map benchmark to result without a dictionary.

I mean for Go developers it's clear which benchmark `github.com/ethereum/go-ethereum/common/bitutil/Encoding4KBVerySparse` path symbolizes, but something like `ethereum/Encoding4KBVerySparse` is less obvious. What if there is multiple `Encoding4KBVerySparse` inside `etherium`?

**Comment by Quasilyte** [comment]
I will workaround this by using shortened path for most long benchmark names for now.
Though it would be still good to have at least 80-100 char limit.

**Comment by Quasilyte** [comment]
Hah, there are some hilarious cases like:
`golang.org/x/crypto/chacha20poly1305/Chacha20Poly1305Seal_1350:Time`

**Comment by tobami** [comment]
@Quasilyte I appreciate the problem, but it's not easy from a UI point of view. We can increase it on the database level, but  how do you propose to truncate names that overflow the left-menu width?

**Comment by Quasilyte** [comment]
I have several potential solutions right now, but it can be better to wait like two or three months before our Codespeed-based app is better understood. Maybe some generally good solution will pop up.

I don't think proposing Go-centric solution is a good thing for Codespeed, so I will keep my horses. :)

This issue may attract other users if they face the same problem, which in turn may result in a more active discussion.

**Comment by tobami** [comment]
Al-right, let's do that!
